apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: esgf-postgres-esgcet
  labels:
    stack: esgf
    component: postgres-esgcet
spec:
  replicas: 1
  selector:
    matchLabels:
      stack: esgf
      component: postgres-esgcet
  template:
    metadata:
      labels:
        stack: esgf
        component: postgres-esgcet
    spec:
      containers:
        - name: postgres-esgcet
          image: esgfhub/postgres:latest
          ports:
            - name: postgres
              containerPort: 5432
          readinessProbe:
            tcpSocket: &probe
              port: 5432
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket: *probe
            initialDelaySeconds: 60
            periodSeconds: 10
          env:
            - name: POSTGRESQL_DATABASE
              value: esgcet
            - name: POSTGRESQL_USER
              value: dbsuper
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: esgf-postgres-esgcet-secrets
                  key: database-password
            - name: ESGF_ESGCET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: esgf-postgres-esgcet-secrets
                  key: database-publisher-password
            - name: ESGF_ROOTADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: esgf-cog-secrets
                  key: rootadmin-password 
            - name: ESGF_ROOTADMIN_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: esgf-config
                  key: root-admin-email
            - name: ESGF_ROOTADMIN_USERNAME
              value: rootAdmin
            - name: ESGF_ROOTADMIN_OPENID
              valueFrom:
                configMapKeyRef:
                  name: esgf-config
                  key: root-admin-openid
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/pgsql/data
      volumes:
        - name: postgres-data
          emptyDir: {}
